lib: [
  "_build/install/default/lib/ppx_make_record/META"
  "_build/install/default/lib/ppx_make_record/Main.a"
  "_build/install/default/lib/ppx_make_record/Main.cma"
  "_build/install/default/lib/ppx_make_record/Main.cmi"
  "_build/install/default/lib/ppx_make_record/Main.cmt"
  "_build/install/default/lib/ppx_make_record/Main.cmx"
  "_build/install/default/lib/ppx_make_record/Main.cmxa"
  "_build/install/default/lib/ppx_make_record/Main.cmxs"
  "_build/install/default/lib/ppx_make_record/Main.ml"
  "_build/install/default/lib/ppx_make_record/dune-package"
  "_build/install/default/lib/ppx_make_record/opam"
]
libexec: [
  "_build/install/default/lib/ppx_make_record/ppx.exe"
]
doc: [
  "_build/install/default/doc/ppx_make_record/LICENSE"
  "_build/install/default/doc/ppx_make_record/README.md"
]
